### ISSUE TITLE
realbutil sync does nothing

### ISSUE THREAD

**Issue by mdaniel** [imperviousinc/beacon#14]
This issue may be "overcome by events" if(when) #8 lands, but for the time being it's confusing that [`realbutil sync`](https://github.com/imperviousinc/beacon/blob/main/tools/src/realbutil/main.go#L339-L342) does nothing but emit help, seemingly because it has no `Action:` associated to it

**Comment by buffrr** [comment]
Upgraded beacon to chrome version 101 so this sync command will be handy. Unfortunately, takes a long time to re-build after updating.
