### ISSUE TITLE
Is there Linux support planned? 

### ISSUE THREAD

**Issue by lucasburlingham** [imperviousinc/beacon#2]
Security and privacy-driven folks are a staple of the Linux desktop community. They are also often accustomed to making support tickets, GH issues, and promoting their favorite software, even if it is still in beta and has paper cuts. 

Is there Linux support planned? Where can we help?

**Comment by FliKites** [comment]
If you know how to build chromium from source, you could technically build the Linux version and make it available :)

**Comment by lucasburlingham** [comment]
Sorry, didn't see the line in the README.
