### ISSUE TITLE
go build causes type error in hns.go

### ISSUE THREAD

**Issue by mdaniel** [imperviousinc/beacon#6]
```
../../third_party/hnsquery/hns.go:83:52: cannot use _Ctype_ulonglong(ctxId) (value of type _Ctype_unsignedlonglong) as type _Ctype_unsignedlong in variable declaration
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-buildmode=c-shared', '-o', '/proj/imperviousinc/src/out/Debug/libbeacon.so']' returned non-zero exit status 2.
```
This is with go1.18.1, but I dunno what version the build is expecting it to be

**Comment by mdaniel** [comment]
for future generations who may see this issue, be aware that the beacon `third_party` directory is built _in place_ and thus `rm -rf src/out/Debug` is only one part, one must also `cd src/beacon/third_party && git clean -xdf .`

**Comment by buffrr** [comment]
You would rarely need to `rm -rf src/out/Debug`. The third party lib looks for the build/ directory in place it's gitignored but it won't get rebuilt if it's already built. Once third_party is moved out of this repo, it will be cleaned up. So future generations, you don't need to know this :D

**Comment by mdaniel** [comment]
> but it won't get rebuilt if it's already built

... which is highly relevant if one is changing non-source components such as the CFLAGS or `go build` command-line, else weird linkage errors will persist
