### ISSUE TITLE
GRD string placeholder DCHECK fails in debug builds

### ISSUE THREAD

**Issue by buffrr** [imperviousinc/beacon#9]
The GRD string in the info bubble expects a placeholder. This crash happens in debug builds clicking on the padlock because of a `DCHECK` :

```
Check failed: std::string::npos != pos .... "Didn't find a $1 placeholder in ..." at l10n_util.cc(795)
```

This should be a simple fix

**Comment by mdaniel** [comment]
You'll be glad to know that I got the Linux build far enough to actually hit this :-D

**Comment by buffrr** [comment]
Woah that's great PRs very welcome!
